-- 物理表: FMBL (SAP 预算录入凭证行)
-- connectionId: duckdb__ods_budget_expense
-- output_variable_name = 预算明细_2025
SELECT
  "/BIC/LOGSYS"     AS 逻辑系统,
  CLIENT            AS 客户端,
  FM_AREA           AS 财务管理范围,
  DOCYEAR           AS 凭证年度,
  DOCNR             AS 凭证编号,
  DOCLN             AS 凭证行号,
  RPMAX             AS 期间,
  FLG_ADDED         AS 附加行标识,
  CTEM_CATEGORY     AS 承诺项类别,
  FISCYEAR          AS 财年,
  CEFFYEAR          AS 现金生效年度,
  FUND              AS 基金,
  BUDGET_PD         AS 预算期间,
  FUNDSCTR          AS 基金中心,
  CMMTITEM          AS 承诺项,
  FUNCAREA          AS 功能范围,
  GRANT_NBR         AS 资助,
  MEASURE           AS 资助项目,
  USERDIM           AS 用户维度,
  BUDCAT            AS 预算类别,
  VALTYPE           AS 值类型,
  PROCESS           AS 预算流程,
  BUDTYPE           AS 预算类型,
  TCURR             AS 交易货币,
  TVAL01            AS 交易金额_01月,
  TVAL02            AS 交易金额_02月,
  TVAL03            AS 交易金额_03月,
  TVAL04            AS 交易金额_04月,
  TVAL05            AS 交易金额_05月,
  TVAL06            AS 交易金额_06月,
  TVAL07            AS 交易金额_07月,
  TVAL08            AS 交易金额_08月,
  TVAL09            AS 交易金额_09月,
  TVAL10            AS 交易金额_10月,
  TVAL11            AS 交易金额_11月,
  TVAL12            AS 交易金额_12月,
  LVAL01            AS 本币金额_01月,
  LVAL02            AS 本币金额_02月,
  LVAL03            AS 本币金额_03月,
  LVAL04            AS 本币金额_04月,
  LVAL05            AS 本币金额_05月,
  LVAL06            AS 本币金额_06月,
  LVAL07            AS 本币金额_07月,
  LVAL08            AS 本币金额_08月,
  LVAL09            AS 本币金额_09月,
  LVAL10            AS 本币金额_10月,
  LVAL11            AS 本币金额_11月,
  LVAL12            AS 本币金额_12月,
  DISTKEY           AS 分配键,
  TEXT50            AS 行文本,
  RID               AS 行ID
FROM FMBL
WHERE FISCYEAR = '2025'
